<?php

namespace Misteryomi\SocialPublisher\Content;

/**
 * The image card copy block: headline with an optional highlighted phrase,
 * a short supporting subtitle line, and an optional list of detail rows.
 *
 * Rows carry facts the caller already holds — listings, figures, names — so the
 * card can show them instead of only a slogan. They are deliberately absent from
 * SocialPostSchema: rows are supplied by the caller, never generated by the model.
 */
final class CardCopy
{
    /**
     * @param  list<array{primary: string, secondary: string}>  $rows
     */
    public function __construct(
        public readonly string $headline,
        public readonly string $highlight = '',
        public readonly string $subtitle = '',
        public readonly string $label = '',
        public readonly array $rows = [],
        public readonly string $company = '',
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            headline:  (string) ($data['headline']  ?? ''),
            highlight: (string) ($data['highlight'] ?? ''),
            subtitle:  (string) ($data['subtitle']  ?? ''),
            label:     (string) ($data['label']     ?? ''),
            rows:      self::normaliseRows($data['rows'] ?? []),
            company:   (string) ($data['company'] ?? ''),
        );
    }

    public function withLabel(string $label): self
    {
        return new self($this->headline, $this->highlight, $this->subtitle, $label, $this->rows, $this->company);
    }

    /**
     * The employer this card is about. Renderers use it for the lead-in and to
     * avoid printing the same name twice; like rows, it is a caller-supplied
     * fact rather than generated copy.
     */
    public function withCompany(string $company): self
    {
        return new self($this->headline, $this->highlight, $this->subtitle, $this->label, $this->rows, trim($company));
    }

    /**
     * @param  array<int, array{primary?: string, secondary?: string}>  $rows
     */
    public function withRows(array $rows): self
    {
        return new self($this->headline, $this->highlight, $this->subtitle, $this->label, self::normaliseRows($rows), $this->company);
    }

    public function hasRows(): bool
    {
        return $this->rows !== [];
    }

    public function toArray(): array
    {
        $card = array_filter([
            'headline'  => $this->headline,
            'highlight' => $this->highlight,
            'subtitle'  => $this->subtitle,
            'label'     => $this->label,
            'company'   => $this->company,
        ], fn ($v) => $v !== '');

        if ($this->rows !== []) {
            $card['rows'] = $this->rows;
        }

        return $card;
    }

    public function isEmpty(): bool
    {
        return $this->headline === '';
    }

    /**
     * Coerce caller-supplied rows into a predictable shape and drop the empty
     * ones, so a renderer never has to guard each field.
     *
     * @return list<array{primary: string, secondary: string}>
     */
    private static function normaliseRows(mixed $rows): array
    {
        if (! is_array($rows)) {
            return [];
        }

        $normalised = [];

        foreach ($rows as $row) {
            if (! is_array($row)) {
                continue;
            }

            $primary = trim((string) ($row['primary'] ?? ''));

            if ($primary === '') {
                continue;
            }

            $normalised[] = [
                'primary'   => $primary,
                'secondary' => trim((string) ($row['secondary'] ?? '')),
            ];
        }

        return $normalised;
    }
}
